import { describe, test, expect, beforeAll, beforeEach } from '@jest/globals';
import { algorandFixture } from '@algorandfoundation/algokit-utils/testing';
import * as algokit from '@algorandfoundation/algokit-utils';
import algosdk from 'algosdk';
import { Arc59Factory, Arc59Client } from '../contracts/clients/Arc59Client';

const fixture = algorandFixture();
algokit.Config.configure({
  populateAppCallResources: true,
  // eslint-disable-next-line no-console
  logger: { error: () => console.error, debug: () => {}, warn: console.warn, info: () => {}, verbose: () => {} },
});

async function getSimulateSender(algorand: algokit.AlgorandClient) {
  return await algorand.account.localNetDispenser();
}

/**
 * Gets information about sending an asset through the ARC59 router to a receiver
 *
 * @param appClient The ARC59 client generated by algokit
 * @param assetId The ID of the asset to send
 * @param receiver The address of the receiver
 * @returns An object containing information about sending the asset, including the number of inner transactions required, the MBR, whether the router and receiver are opted in, and how much ALGO the receiver would need to claim the asset
 */
async function arc59GetSendAssetInfo({
  algorand,
  appId,
  sender,
  assetId,
  receiver,
  signer,
}: {
  algorand: algokit.AlgorandClient;
  appId: bigint;
  sender: algosdk.Address;
  assetId: bigint;
  receiver: algosdk.Address;
  signer?: algosdk.TransactionSigner;
}): Promise<{
  itxns: bigint;
  mbr: bigint;
  routerOptedIn: boolean;
  receiverOptedIn: boolean;
  receiverAlgoNeededForClaim: bigint;
}> {
  const appClient = algorand.client.getTypedAppClientById(Arc59Client, {
    appId,
    defaultSender: sender,
    defaultSigner: signer,
  });

  const [itxns, mbr, routerOptedIn, receiverOptedIn, receiverAlgoNeededForClaim] = (
    await appClient
      .newGroup()
      .arc59GetSendAssetInfo({ args: { asset: assetId, receiver: receiver.toString() } })
      .simulate({ allowUnnamedResources: true })
  ).returns[0]!;

  return {
    itxns,
    mbr,
    routerOptedIn,
    receiverOptedIn,
    receiverAlgoNeededForClaim,
  };
}

/**
 * Send an asset to a receiver using the ARC59 router
 *
 * @param algorand The AlgorandClient instance to use to send transactions
 * @param appId The ARC59 application ID
 * @param assetId The ID of the asset to send
 * @param sender The address of the sender
 * @param receiver The address of the receiver
 * @param signer The optional signer to sign the transactions
 */
async function arc59SendAsset({
  algorand,
  appId,
  assetId,
  sender,
  receiver,
  signer,
}: {
  algorand: algokit.AlgorandClient;
  appId: bigint;
  assetId: bigint;
  sender: algosdk.Address;
  receiver: algosdk.Address;
  signer?: algosdk.TransactionSigner;
}) {
  const appClient = algorand.client.getTypedAppClientById(Arc59Client, {
    appId,
    defaultSender: sender,
    defaultSigner: signer,
  });

  // Get the address of the ARC59 router
  const arc59RouterAddress = appClient.appAddress;

  const { itxns, mbr, routerOptedIn, receiverOptedIn, receiverAlgoNeededForClaim } = await arc59GetSendAssetInfo({
    algorand,
    appId,
    sender,
    assetId,
    receiver,
    signer,
  });

  // If the receiver has opted in, just send the asset directly
  if (receiverOptedIn) {
    await algorand.send.assetTransfer({
      sender,
      receiver,
      assetId,
      amount: 1n,
    });

    return;
  }

  // Create a composer to form an atomic transaction group
  const group = appClient.newGroup();

  // If the MBR is non-zero, send the MBR to the router
  if (mbr || receiverAlgoNeededForClaim) {
    const mbrPayment = await algorand.createTransaction.payment({
      sender,
      receiver: arc59RouterAddress,
      amount: algokit.microAlgos(Number(mbr + receiverAlgoNeededForClaim)),
    });

    group.addTransaction(mbrPayment);
  }

  // If the router is not opted in, add a call to arc59OptRouterIn to do so
  if (!routerOptedIn) group.arc59OptRouterIn({ args: { asa: assetId } });

  /** The box of the receiver's pubkey will always be needed */
  const resources = { boxReferences: [receiver.publicKey] };

  /** The address of the receiver's inbox */
  const inboxAddress = (
    await appClient
      .newGroup()
      .arc59GetInbox({ args: { receiver: receiver.toString() }, ...resources })
      .simulate()
  ).returns[0]!;

  // The transfer of the asset to the router
  const axfer = await algorand.createTransaction.assetTransfer({
    sender,
    receiver: arc59RouterAddress,
    assetId,
    amount: 1n,
  });

  // An extra itxn is if we are also sending ALGO for the receiver claim
  const totalItxns = itxns + (receiverAlgoNeededForClaim === 0n ? 0n : 1n);

  group.arc59SendAsset({
    args: { axfer, receiver: receiver.toString(), additionalReceiverFunds: receiverAlgoNeededForClaim },
    extraFee: algokit.microAlgos(1000 * Number(totalItxns)),
    ...resources,
    accountReferences: [receiver, inboxAddress],
    assetReferences: [assetId],
  });

  await group.send({ populateAppCallResources: false });
}

/**
 * Claim an asset from the ARC59 inbox
 *
 * @param algorand The AlgorandClient instance to use to send transactions
 * @param appId The ARC59 application ID
 * @param assetId The ID of the asset to claim
 * @param claimer The address of the account claiming the asset
 * @param signer The optional signer to sign the transactions
 */
async function arc59Claim({
  algorand,
  appId,
  assetId,
  claimer,
  signer,
}: {
  algorand: algokit.AlgorandClient;
  appId: bigint;
  assetId: bigint;
  claimer: algosdk.Address;
  signer?: algosdk.TransactionSigner;
}) {
  // Create appClient for actual transactions with claimer as sender
  const appClient = algorand.client.getTypedAppClientById(Arc59Client, {
    appId,
    defaultSender: claimer,
    defaultSigner: signer,
  });

  const group = appClient.newGroup();

  // Check if the claimer has opted in to the asset
  let claimerOptedIn = false;
  try {
    await algorand.asset.getAccountInformation(claimer, assetId);
    claimerOptedIn = true;
  } catch (e) {
    // Do nothing
  }

  const inbox = (
    await appClient
      .newGroup()
      .arc59GetInbox({ sender: await getSimulateSender(algorand), args: { receiver: claimer.toString() } })

      .simulate({ allowUnnamedResources: true, allowEmptySignatures: true, fixSigners: true })
  ).returns[0]!;

  let totalTxns = 3;

  const resources = {
    boxReferences: [claimer.publicKey],
    accountReferences: [inbox],
    assetReferences: [] as bigint[], // This is left empty for now because it's not needed for claimAlgo
  };

  // If the inbox has extra ALGO, claim it
  const inboxInfo = await algorand.account.getInformation(inbox);
  if (inboxInfo.minBalance < inboxInfo.balance) {
    totalTxns += 2;
    group.arc59ClaimAlgo({ sender: claimer, args: [], staticFee: (0).algo(), ...resources });
  }

  // If the claimer hasn't already opted in, add a transaction to do so
  if (!claimerOptedIn) {
    group.addTransaction(await algorand.createTransaction.assetOptIn({ assetId, sender: claimer }));
  }

  resources.assetReferences.push(assetId);

  group.arc59Claim({
    args: { asa: assetId },
    extraFee: algokit.microAlgos(1000 * (totalTxns - 1)),
    sender: claimer,
    ...resources,
  });

  await group.send({ populateAppCallResources: false });
}

describe('Arc59', () => {
  let appClient: Arc59Client;
  let assetOne: bigint;
  let assetTwo: bigint;
  let alice: algosdk.Account;
  let bob: algosdk.Account;
  let algorand: algokit.AlgorandClient;

  beforeEach(fixture.beforeEach);

  beforeAll(async () => {
    await fixture.beforeEach();
    const { testAccount } = fixture.context;
    algorand = fixture.algorand;

    const factory = new Arc59Factory({ algorand, defaultSender: testAccount });

    appClient = (await factory.send.create.createApplication({ args: [] })).appClient;

    const oneResult = await algorand.send.assetCreate({
      sender: testAccount.addr,
      unitName: 'one',
      total: 100n,
    });

    assetOne = BigInt(oneResult.confirmation.assetIndex!);

    const twoResult = await algorand.send.assetCreate({
      sender: testAccount.addr,
      unitName: 'two',
      total: 100n,
    });
    assetTwo = BigInt(twoResult.confirmation.assetIndex!);

    alice = testAccount;

    await appClient.appClient.fundAppAccount({ amount: algokit.microAlgos(100_000), note: 'initial funding' });
  });

  test('routerOptIn', async () => {
    await appClient.appClient.fundAppAccount({ amount: algokit.microAlgos(100_000) });
    await appClient.send.arc59OptRouterIn({ args: { asa: assetOne }, extraFee: algokit.microAlgos(1_000) });

    const routerBalance = (await algorand.asset.getAccountInformation(appClient.appAddress, assetOne)).balance;
    expect(routerBalance).toBe(0n);
  });

  test('Brand new account getSendAssetInfo', async () => {
    const res = await appClient.send.arc59GetSendAssetInfo({
      args: { asset: assetOne, receiver: algosdk.generateAccount().addr.toString() },
      extraFee: algokit.microAlgos(1_000),
    });

    const [
      itxns,
      mbr,
      routerOptedIn,
      receiverOptedIn,
      receiverAlgoNeededForClaim,
      receiverAlgoNeededForWorstCaseClaim,
    ] = res.return!;

    expect(itxns).toBe(5n);
    expect(mbr).toBe(228_100n);
    expect(routerOptedIn).toBe(true);
    expect(receiverOptedIn).toBe(false);
    expect(receiverAlgoNeededForClaim).toBe(201_000n);
    expect(receiverAlgoNeededForWorstCaseClaim).toBe(201_000n);
  });

  test('Brand new account sendAsset', async () => {
    const { testAccount } = fixture.context;
    bob = testAccount;
    algorand.account.setSignerFromAccount(bob);

    await arc59SendAsset({
      algorand,
      appId: appClient.appId,
      assetId: assetOne,
      sender: alice.addr,
      receiver: bob.addr,
    });
  });

  test('Existing inbox sendAsset (existing asset)', async () => {
    await arc59SendAsset({
      algorand,
      appId: appClient.appId,
      assetId: assetOne,
      sender: alice.addr,
      receiver: bob.addr,
    });
  });

  test('Existing inbox sendAsset (new asset)', async () => {
    await arc59SendAsset({
      algorand,
      appId: appClient.appId,
      assetId: assetTwo,
      sender: alice.addr,
      receiver: bob.addr,
    });
  });

  test('claim', async () => {
    await arc59Claim({ algorand, appId: appClient.appId, assetId: assetOne, claimer: bob.addr });

    const bobAssetInfo = await algorand.asset.getAccountInformation(bob.addr, assetOne);

    expect(bobAssetInfo.balance).toBe(2n);
  });

  test('reject', async () => {
    const newAsset = BigInt(
      (await algorand.send.assetCreate({ sender: alice.addr, total: 1n })).confirmation.assetIndex!
    );
    await arc59SendAsset({
      algorand,
      appId: appClient.appId,
      assetId: newAsset,
      sender: alice.addr,
      receiver: bob.addr,
    });

    await appClient.send.arc59Reject({
      sender: bob.addr,
      args: { asa: newAsset },
      extraFee: algokit.microAlgos(2_000),
    });
  });

  test('claim from 0-ALGO account', async () => {
    const receiver = algorand.account.random();

    await arc59SendAsset({
      algorand,
      appId: appClient.appId,
      assetId: assetOne,
      sender: alice.addr,
      receiver: receiver.addr,
    });

    await arc59Claim({ algorand, appId: appClient.appId, assetId: assetOne, claimer: receiver.addr });

    const receiverAssetInfo = await algorand.asset.getAccountInformation(receiver.addr, assetOne);

    expect(receiverAssetInfo.balance).toBe(1n);
  });

  test('two claims from 0-ALGO account', async () => {
    const receiver = algorand.account.random();
    await arc59SendAsset({
      algorand,
      appId: appClient.appId,
      assetId: assetOne,
      sender: alice.addr,
      receiver: receiver.addr,
    });
    await arc59SendAsset({
      algorand,
      appId: appClient.appId,
      assetId: assetTwo,
      sender: alice.addr,
      receiver: receiver.addr,
    });

    await arc59Claim({ algorand, appId: appClient.appId, assetId: assetOne, claimer: receiver.addr });
    await arc59Claim({ algorand, appId: appClient.appId, assetId: assetTwo, claimer: receiver.addr });

    const receiverAssetInfoOne = await algorand.asset.getAccountInformation(receiver.addr, assetOne);
    const receiverAssetInfoTwo = await algorand.asset.getAccountInformation(receiver.addr, assetTwo);

    expect(receiverAssetInfoOne.balance).toBe(1n);
    expect(receiverAssetInfoTwo.balance).toBe(1n);
  });

  test('claim from abnormal ALGO balance', async () => {
    const receiver = algorand.account.random();

    await algorand.send.payment({ sender: alice.addr, receiver: receiver.addr, amount: algokit.microAlgos(123_456) });

    await arc59SendAsset({
      algorand,
      appId: appClient.appId,
      assetId: assetOne,
      sender: alice.addr,
      receiver: receiver.addr,
    });
    await arc59Claim({ algorand, appId: appClient.appId, assetId: assetOne, claimer: receiver.addr });

    const receiverAssetInfo = await algorand.asset.getAccountInformation(receiver.addr, assetOne);

    expect(receiverAssetInfo.balance).toBe(1n);
  });

  test('arc59GetSendAssetInfo with small amount of ALGO in inbox', async () => {
    const receiver = algorand.account.random();

    await arc59SendAsset({
      algorand,
      appId: appClient.appId,
      assetId: assetOne,
      sender: alice.addr,
      receiver: receiver.addr,
    });
    await arc59Claim({ algorand, appId: appClient.appId, assetId: assetOne, claimer: receiver.addr });

    const inbox = (
      await appClient
        .newGroup()
        .arc59GetInbox({ args: { receiver: receiver.addr.toString() } })
        .simulate({ allowUnnamedResources: true })
    ).returns[0]!;

    await algorand.send.payment({
      sender: alice.addr,
      receiver: inbox,
      amount: algokit.microAlgos(1),
    });

    await appClient
      .newGroup()
      .arc59GetSendAssetInfo({ args: { asset: assetTwo, receiver: receiver.addr.toString() } })
      .simulate({ allowUnnamedResources: true });
  });
});
